# Generated by Django 4.1.4 on 2022-12-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='taggeg_pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
