# Generated by Django 4.1.4 on 2022-12-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='taggeg_pets',
            new_name='tagged_pets',
        ),
    ]
