# Generated by Django 4.1.5 on 2023-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_appuser_first_name_alter_appuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("DoNotShow", "Do no show"),
                ],
                max_length=9,
            ),
        ),
    ]
